name: SkyBlockCo-Op
main: nz.Tzeentchful.SkyBlock.skySMP
version: 1.5
description: skyIsland SMP mod. Survive on a small island in the sky with only basic supplies. Try to beat the challenges.
softdepend: [CleanroomGenerator]
depend: [WorldGuard, WorldEdit]
author: Tzeentchful & thekillerofevil
commands:
    skyblock:
        description: All commands for Skyblock Co-Op
        usage: /skyblock help
        aliases: sb
